### PR TITLE
Make ui_calculator a Python package

### PR DESCRIPTION
**Pull request by MaxGhenis**
Thanks for the great scripts! I wanted to use them in a package without relying on running it from the right folder structure, so added the necessary components to make it installable. Here's a full set of changes:
* Make `ui_calculator` package using `setup.py` and reorganizing files as required for packaging.
* Add a simple `pytest` test, checking that the function produces the expected result on the sample yearly data
* Update all examples to use the package
* Various code style and typo fixes (e.g. ensuring 80-character lines)
* Add GitHub's default Python `.gitignore` and remove `.pyc` file which is typically ignored for GitHub

You can see it in action in [this Colab notebook](https://colab.research.google.com/drive/1JKjwZODPNY5Cn9hyY4XVpZz33ZSEqkyv?usp=sharing), which installs the package from GitHub, loads sample data from GitHub, and runs the code to calculate benefits.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Hi - just wanted to check in here on this. Is this something the maintainers are interested in? If so I can resolve the merge conflicts.

**Comment by ganong123** [comment]
@MaxGhenis I'm sorry for the delay. Yes, this is a fantastic change. please do resolve the merge conflicts and then I will go ahead and merge.

**Comment by ganong123** [comment]
Also, I never knew about colab before and have never made a package before. good stuff!

FYI @peterobertson we will likely want to eventually update the R scripts that call Python in `covid_inc_sprt` to capture this change in `ui_calculator`

FYI @roshanm9 I do not think we need to update https://github.com/ganong-noel/ui_rep_rate

**Comment by MaxGhenis** [comment]
Thanks @ganong123, I resolved the merge conflicts and verified the tests run locally, so this is now ready to go.

I also added a GitHub Action to automatically test in pull requests, and a badge to show the build status, but it looks like that will only take effect in a subsequent PR. It usually activates within the PR it's added to, but might not here because GitHub Actions haven't been activated in the repo, or because I don't have write access.

**Comment by MaxGhenis** [comment]
The GitHub Action for testing works on my branch: https://github.com/MaxGhenis/ui_calculator/actions/runs/253051908

**Review by ganong123 — APPROVED** [review]

**Comment by ganong123** [comment]
@MaxGhenis thanks for your work here!

**Pull request merged**
